import React,{useEffect,useState}from'react';
import{SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView,TextInput}from'react-native';
import{StatusBar}from'expo-status-bar';
import AsyncStorage from'@react-native-async-storage/async-storage';
const P='#ff1493',CY='#00f5ff',PU='#a855f7',BK='#07070a',CD='#15151c',TX='#fff7fb',M='#a8a8b3',TAN='#d6a66f';
const tabs=['Home','Me','Coach','Create','Goals','Journey'];
const moods=['LOW','MEH','OKAY','GOOD','GREAT'];
const habits=['Morning reset','Move my body','Do one thing for future me'];
function Card({title,children,cyan=false}){return <View style={[s.card,cyan&&s.cyan]}><Text style={[s.ct,cyan&&{color:CY}]}>{title}</Text>{children}</View>}
function Header(){return <View style={s.head}><View style={s.print}><Text style={s.spots}>●  ◉   ● ◉  ●   ◉</Text></View><Text style={s.logo}>PINKPRINT</Text><Text style={s.tag}>YOUR LIFE • YOUR PATTERNS • YOUR BLUEPRINT</Text></View>}
export default function App(){
 const[tab,setTab]=useState('Home'),[journal,setJournal]=useState(''),[entries,setEntries]=useState([]),[goal,setGoal]=useState(''),[goals,setGoals]=useState([]),[focus,setFocus]=useState(''),[mood,setMood]=useState(''),[done,setDone]=useState([]),[xp,setXp]=useState(0);
 useEffect(()=>{(async()=>{setEntries(JSON.parse(await AsyncStorage.getItem('entries')||'[]'));setGoals(JSON.parse(await AsyncStorage.getItem('goals')||'[]'));setFocus(await AsyncStorage.getItem('focus')||'');setMood(await AsyncStorage.getItem('mood')||'');setDone(JSON.parse(await AsyncStorage.getItem('habits')||'[]'));setXp(Number(await AsyncStorage.getItem('xp')||0))})()},[]);
 const store=async(k,v)=>AsyncStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));
 const saveEntry=async()=>{if(!journal.trim())return;let n=[{text:journal.trim(),date:new Date().toLocaleString()},...entries];setEntries(n);store('entries',n);setJournal('');setXp(x=>{store('xp',x+10);return x+10})};
 const addGoal=async()=>{if(!goal.trim())return;let n=[{text:goal.trim(),done:false},...goals];setGoals(n);store('goals',n);setGoal('')};
 const toggleGoal=i=>{let n=goals.map((g,x)=>x===i?{...g,done:!g.done}:g);setGoals(n);store('goals',n)};
 const toggleHabit=h=>{let n=done.includes(h)?done.filter(x=>x!==h):[...done,h];setDone(n);store('habits',n);if(!done.includes(h))setXp(x=>{store('xp',x+5);return x+5})};
 const chooseMood=m=>{setMood(m);store('mood',m)};
 const saveFocus=t=>{setFocus(t);store('focus',t)};
 const level=Math.floor(xp/100)+1;
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><Header/><ScrollView contentContainerStyle={s.body}>
 {tab==='Home'&&<><Text style={s.hero}>YOUR DAY, YOUR WAY.</Text><Text style={s.sub}>Small choices. Real progress. No perfection required.</Text><Card title="TODAY'S FOCUS"><TextInput value={focus} onChangeText={saveFocus} placeholder="What matters most today?" placeholderTextColor="#666" style={s.input}/></Card><Card title="QUICK CHECK-IN" cyan><Text style={s.text}>How are you feeling?</Text><View style={s.chips}>{moods.map(m=><Pressable key={m} onPress={()=>chooseMood(m)} style={[s.chip,mood===m&&s.chipOn]}><Text style={[s.chipText,mood===m&&{color:BK}]}>{m}</Text></Pressable>)}</View></Card><Card title="DAILY RESET">{habits.map(h=><Pressable key={h} onPress={()=>toggleHabit(h)} style={s.line}><Text style={[s.box,done.includes(h)&&{color:CY}]}>{done.includes(h)?'◆':'◇'}</Text><Text style={[s.text,done.includes(h)&&s.done]}>{h}</Text></Pressable>)}</Card><View style={s.row}><View style={s.stat}><Text style={s.num}>{xp}</Text><Text style={s.dim}>XP • LEVEL {level}</Text></View><View style={s.stat}><Text style={[s.num,{color:CY}]}>{goals.filter(g=>g.done).length}</Text><Text style={s.dim}>GOALS DONE</Text></View></View><Card title="TODAY'S AFFIRMATION"><Text style={s.quote}>“I can build my life one honest choice at a time.”</Text></Card></>}
 {tab==='Me'&&<><Text style={s.hero}>MY BLUEPRINT</Text><Card title="SELF-DISCOVERY"><Text style={s.text}>What feels like me when nobody else is choosing?</Text></Card><Card title="LIFE AREAS" cyan><Text style={s.text}>Self • Style • Relationships • Home • Money • Career • Creativity • Fun</Text></Card><Card title="VALUES + IDENTITY"><Text style={s.dim}>A space to discover, edit and refine what genuinely matters to you—without PINKPRINT deciding for you.</Text></Card></>}
 {tab==='Coach'&&<><Text style={s.hero}>COACH</Text><Card title="WHAT DO YOU NEED?" cyan><Text style={s.text}>Reflect • Plan • Get unstuck • Build confidence • Goals • Habits • Career • Money</Text></Card><Card title="AI COACH"><Text style={s.dim}>The coach interface lives here. We'll connect the actual AI brain without locking the rest of PINKPRINT behind a subscription.</Text></Card></>}
 {tab==='Create'&&<><Text style={s.hero}>CREATE</Text><Text style={s.sub}>Your private creative studio.</Text><Pressable onPress={()=>setTab('Journal')}><Card title="JOURNAL"><Text style={s.text}>Write freely, reflect, save memories and turn an entry into something more.</Text></Card></Pressable><Card title="VISION STUDIO" cyan><Text style={s.text}>Freeform scrapbook-style vision boards.</Text><Text style={s.dim}>Photos • text • quotes • layers • backgrounds • doodles • links</Text></Card><Card title="BLOG STUDIO"><Text style={s.text}>Your WordPress command center.</Text><Text style={s.dim}>Ideas • drafts • editor • media • categories • tags • calendar • SEO • preview • publish</Text></Card></>}
 {tab==='Journal'&&<><Text style={s.hero}>JOURNAL</Text><TextInput multiline value={journal} onChangeText={setJournal} placeholder="What's on your mind?" placeholderTextColor="#666" style={[s.input,{minHeight:130}]}/><Pressable style={s.btn} onPress={saveEntry}><Text style={s.btnText}>SAVE ENTRY  +10 XP</Text></Pressable>{entries.map((e,i)=><Card key={i} title={e.date}><Text style={s.text}>{e.text}</Text></Card>)}</>}
 {tab==='Goals'&&<><Text style={s.hero}>GOALS</Text><TextInput value={goal} onChangeText={setGoal} placeholder="Something I want to build..." placeholderTextColor="#666" style={s.input}/><Pressable style={s.btn} onPress={addGoal}><Text style={s.btnText}>ADD GOAL</Text></Pressable>{goals.map((g,i)=><Pressable key={i} onPress={()=>toggleGoal(i)}><Card title={g.done?'◆ COMPLETE':'◇ IN PROGRESS'}><Text style={[s.text,g.done&&s.done]}>{g.text}</Text></Card></Pressable>)}</>}
 {tab==='Journey'&&<><Text style={s.hero}>MY JOURNEY</Text><Card title="CURRENT CHAPTER" cyan><Text style={s.text}>Level {level} • {xp} XP</Text><Text style={s.dim}>Your story grows as you actually live it.</Text></Card>{entries.slice(0,5).map((e,i)=><Card key={i} title={e.date}><Text style={s.text}>Journal • {e.text}</Text></Card>)}{!entries.length&&<Card title="THE BEGINNING"><Text style={s.dim}>Your journal entries, wins, milestones and discoveries will form your timeline here.</Text></Card>}</>}
 </ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.nav} contentContainerStyle={s.navIn}>{tabs.map(t=><Pressable key={t} onPress={()=>setTab(t)} style={[s.navBtn,tab===t&&s.navOn]}><Text style={[s.navText,tab===t&&s.navTextOn]}>{t}</Text></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BK},head:{backgroundColor:'#0b0b10',paddingHorizontal:18,paddingTop:8,paddingBottom:13,borderBottomWidth:2,borderBottomColor:P,overflow:'hidden'},print:{position:'absolute',right:-8,top:-8,width:145,height:80,backgroundColor:TAN,transform:[{rotate:'-8deg'}],opacity:.9},spots:{fontSize:25,color:'#24150d',letterSpacing:3,padding:9},logo:{color:P,fontSize:30,fontWeight:'900',letterSpacing:2,textShadowColor:PU,textShadowRadius:10},tag:{color:CY,fontSize:9,fontWeight:'800',letterSpacing:1.2},body:{padding:18,paddingBottom:32},hero:{color:TX,fontSize:28,fontWeight:'900',letterSpacing:.5,textShadowColor:P,textShadowRadius:8},sub:{color:M,marginTop:4,marginBottom:16,fontSize:13},card:{backgroundColor:CD,borderRadius:20,padding:17,marginBottom:13,borderWidth:1,borderColor:'#39303b'},cyan:{borderColor:CY},ct:{color:P,fontWeight:'900',fontSize:12,letterSpacing:1.4,marginBottom:9},text:{color:TX,fontSize:15,lineHeight:22},dim:{color:M,fontSize:12,lineHeight:18,marginTop:4},input:{backgroundColor:'#0c0c11',color:TX,minHeight:55,borderRadius:15,padding:14,borderWidth:1,borderColor:'#35353e',textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},chip:{borderWidth:1,borderColor:PU,borderRadius:20,paddingHorizontal:10,paddingVertical:8},chipOn:{backgroundColor:CY,borderColor:CY},chipText:{color:TX,fontSize:10,fontWeight:'900'},line:{flexDirection:'row',alignItems:'center',paddingVertical:8},box:{color:P,fontSize:19,marginRight:10},done:{textDecorationLine:'line-through',opacity:.5},row:{flexDirection:'row',gap:12,marginBottom:13},stat:{flex:1,backgroundColor:CD,borderRadius:20,padding:16,borderWidth:1,borderColor:PU},num:{color:P,fontSize:30,fontWeight:'900'},quote:{color:TX,fontSize:18,fontWeight:'700',fontStyle:'italic',lineHeight:26},btn:{backgroundColor:P,borderRadius:16,padding:15,alignItems:'center',marginBottom:16,shadowColor:P,shadowOpacity:.7,shadowRadius:9,elevation:5},btnText:{color:'#fff',fontWeight:'900',letterSpacing:1},nav:{maxHeight:64,backgroundColor:'#0b0b10',borderTopWidth:1,borderTopColor:'#33243a'},navIn:{paddingHorizontal:8,alignItems:'center',gap:3},navBtn:{paddingVertical:11,paddingHorizontal:13,borderRadius:17},navOn:{backgroundColor:P},navText:{color:'#8e8e9a',fontWeight:'800',fontSize:12},navTextOn:{color:'#fff'}});